sudo: false
language: php
php:
- '5.4'
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache
env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
install: true
script: ./scripts/travis-script.sh
before_deploy:
- make install
- make clean
- make build
- make package
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: onAir.tar.gz
  skip_cleanup: true
  on:
    tags: true
