<?php
/**
 * @file onair_feed.module
 */

/**
 * Implements hook_menu.
 */
function onair_feed_menu() {
  $items['feed/%onair_podcast_machine_name/rss.xml'] = array(
    'title' => 'Generated RSS feed',
    'page callback' => 'onair_feed_rss_page_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'file' => 'onair_feed.page.inc',
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implements hook_theme.
 */
function onair_feed_theme($existing, $type, $theme, $path) {
  $themes['onair_feed_rss'] = array(
    'arguments' => array('podcast' => null),
    'path' => $path . '/theme',
    'file' => 'theme.inc',
    'template' => 'onair-feed-rss',
  );
  return $themes;
}

/**
 * Helper function to generate feed URL of a given podcast object.
 */
function onair_feed_feed_url($entity) {
  $podcast = entity_metadata_wrapper('node', $entity);

  if (!empty($podcast->field_name->value())) {
    $path = "feed/{$podcast->field_name->value()['machine']}/rss.xml";
    return url($path, array('absolute' => TRUE));
  }
}
