<?php
/**
 * @file onair_feed.module
 */

/**
 * Implements hook_menu.
 */
function onair_feed_menu() {
  $items['feed/%onair_podcast_machine_name/rss.xml'] = array(
    'title' => 'Generated RSS feed',
    'page callback' => 'onair_feed_rss_page_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implements hook_theme.
 */
function onair_feed_theme($existing, $type, $theme, $path) {
  $themes['onair_feed_rss'] = array(
    'arguments' => array('podcast' => null),
    'path' => $path . '/theme',
    'file' => 'theme.inc',
    'template' => 'onair-feed-rss',
  );
  return $themes;
}

/**
 * Page callback.
 */
function onair_feed_rss_page_callback($podcast) {
  // Set Content-Type headers if they haven't already been set.
  if (is_null(drupal_get_http_header('Content-Type'))) {
    drupal_add_http_header('Content-Type', 'application/rss+xml; charset=utf-8');
  }

  // Set Content-Language headers if they haven't already been set.
  if (is_null(drupal_get_http_header('Content-Language'))) {
    global $language;
    drupal_add_http_header('Content-Language', $language->language);
  }

  $output = theme('onair_feed_rss', array('podcast' => $podcast));
  print tidy_repair_string($output, array(
    'output-xml' => true,
    'input-xml' => true,
    'indent' => true,
    'wrap' => 0,
));
  drupal_page_footer();
  exit;
}
