<?php
/**
 * @file
 * onair_podcast.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function onair_podcast_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-podcast-field_ref_network'.
  $field_instances['node-podcast-field_ref_network'] = array(
    'bundle' => 'podcast',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_ref_network',
    'label' => 'Network',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => -4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Network');

  return $field_instances;
}
